# roles/deploy/tasks/main.yml

# Update system packages
- name: Update all packages
  ansible.builtin.shell: sudo yum update -y
  become: yes

# Install required packages
- name: Install docker, git, python3, and pip
  ansible.builtin.shell: sudo yum install -y docker git python3 python3-pip
  become: yes

# Ensure Docker service is running
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes

# Pull the Docker image from DockerHub
- name: Pull Docker image
  ansible.builtin.shell: docker pull {{ dockerhub_username }}/{{ docker_image_name }}
  become: yes

# Stop and remove existing container if it exists
- name: Stop and remove existing container if it exists
  ansible.builtin.shell: docker rm -f roadmap_ai_backend || true
  become: yes

# Run the Docker container
- name: Run Docker container
  ansible.builtin.shell: |
    docker run -d \
      --name roadmap_ai_backend \
      -p {{ container_port }}:{{ container_port }} \
      --env-file /home/.env \
      {{ dockerhub_username }}/{{ docker_image_name }}
  become: yes
